

class RpcErrors:
    NOT_FOUND = 1
    ALREADY_EXISTS = 2
    NOT_AUTHORIZED = 3
    PERMISSION_DENIED = 4
    FAILED_PRECONDITION = 5
    UNIMPLEMENTED = 6
    UNAVAILABLE = 7
    INTERNAL = 8
